### ISSUE TITLE
Compilation error on windows 10

### ISSUE THREAD

**Issue by JianpingCAI** [dwgoon/jpegio#11]
Need to modify the setup.py a little bit to resolve "cannot find *.lib" error,
`   # DIR_SIMD_HEADER = pjoin(DIR_ROOT, "jpegio", "simd", os_arch,  "include")
    # DIR_SIMD_LIB = pjoin(DIR_ROOT, "jpegio", "simd", os_arch,  "lib")
    DIR_SIMD_HEADER = pjoin(DIR_ROOT, "jpegio", "simd", "include")
    DIR_SIMD_LIB = pjoin(DIR_ROOT, "jpegio", "simd", "lib")`

**Comment by dwgoon** [comment]
Thanks for letting me know this problem.
