### ISSUE TITLE
Fails on colab

### ISSUE THREAD

**Issue by abhinavtripathi95** [dwgoon/jpegio#12]
## Error
module 'jpegio' has no attribute 'read'

## Code to reproduce
Start a google colab session and type
```
! git clone https://github.com/dwgoon/jpegio.git
%cd jpegio/
!python setup.py install
%cd .. 

import jpegio
out = jpegio.read('img.jpg')
```
This will show you the error
```
AttributeError: module 'jpegio' has no attribute 'read'
```

**Comment by dwgoon** [comment]
After installing, restart your colab session, and try again, please.

**Comment by abhinavtripathi95** [comment]
Thanks, @dwgoon !
It works after restarting the colab session. I'm closing this issue.

**Comment by dwgoon** [comment]
Good! :)
