### ISSUE TITLE
An error about import

### ISSUE THREAD

**Issue by KQL11** [dwgoon/jpegio#21]
Hi, dwgoon. I'm grateful to your project. However, after installation, I get an error like this

"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pubdata/linkaiqing/python_package/jpegio-master/jpegio/__init__.py", line 6, in <module>
    from .componentinfo import ComponentInfo
ModuleNotFoundError: No module named 'jpegio.componentinfo'
"
Please add "import cython" to "__init__.py", and "jpegio" is really a  good tool.

**Comment by dwgoon** [comment]
Could you please let me know the directory path you have executed the source code?
You can encounter this kind of error if you execute your sources in the directory of JPEG repo.

**Comment by KQL11** [comment]
Of course. "/home/linkaiqing/code/SI_Steg/train.py" is my source code. “/pubdata/linkaiqing/python_package/jpegio-master” is the jpegio code. After installing the JPEG repo, I run this code in my anaconda environment in "/home/linkaiqing/anaconda3/envs/pytorch". Thanks for your help again, I'm really sorry because of my late reply.

**Comment by KQL11** [comment]
Of course. 

- "/home/linkaiqing/code/SI_Steg/train.py" is my source code. 

- “/pubdata/linkaiqing/python_package/jpegio-master” is the jpegio code.

-  After installing the JPEG repo, I run this code in my anaconda environment in "/home/linkaiqing/anaconda3/envs/pytorch". 

Thanks for your help again, I'm really sorry because of my late reply.

**Comment by dwgoon** [comment]
How did you install jpegio?
I recommend compiling and installing directly from this repository.

**Comment by KQL11** [comment]
I execute the command "python setup.py install" like your README.md. Now I can use the repository successfully, thank you!

**Comment by dwgoon** [comment]
@KQL11 Good job! :)
