### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by wowpocak** [dwgoon/jpegio#3]
Hello,

When I try to import jpegio I receive the following error all the time:

```
>>> import jpegio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bertalan/anaconda3/envs/test/lib/python3.6/site-packages/jpegio-0.2.1-py3.6-linux-x86_64.egg/jpegio/__init__.py", line 7, in <module>
    from .decompressedjpeg import DecompressedJpeg
ImportError: /home/bertalan/anaconda3/envs/test/lib/python3.6/site-packages/jpegio-0.2.1-py3.6-linux-x86_64.egg/jpegio/decompressedjpeg.cpython-36m-x86_64-linux-gnu.so: undefined symbol: jpeg_write_coefficients

```

I have the following specifications:

- Ubuntu 18.04
- Python 3.6
- Conda as dependency manager

I tried installed with the wheel and the setup.py install aswell but neither worked. Could you help me with this please? Thanks!

**Comment by dwgoon** [comment]
I recommend you to install by compiling: 'python setup.py install' In which direcotory have you tried importing the package?

**Comment by wowpocak** [comment]
I installed with "python setup.py install" in the /tmp directory. Could that have caused problems? It still does not work

**Comment by dwgoon** [comment]
@wowpocak 
I've fixed the settings for linux, and uploaded the wheels.
Thanks for letting me know this error.
