### ISSUE TITLE
Error in setup.py

### ISSUE THREAD

**Issue by albertobagnacani** [dwgoon/jpegio#8]
Hi,

when I try to run the installation via `python setup.py install` I got this:
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    os_arch = "mac_x%d"%(arch)
TypeError: %d format: a number is required, not str

It works if I change the string with:
os_arch = "mac_x64"

I have a macOS Catalina 10.15.4.

**Comment by dwgoon** [comment]
Thanks for your report.
I will revise the setup.py script.
